require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/symptoms", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Symptom. As you add validations to Symptom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Symptom.create! valid_attributes
      get symptoms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      symptom = Symptom.create! valid_attributes
      get symptom_url(symptom)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_symptom_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      symptom = Symptom.create! valid_attributes
      get edit_symptom_url(symptom)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Symptom" do
        expect {
          post symptoms_url, params: { symptom: valid_attributes }
        }.to change(Symptom, :count).by(1)
      end

      it "redirects to the created symptom" do
        post symptoms_url, params: { symptom: valid_attributes }
        expect(response).to redirect_to(symptom_url(Symptom.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Symptom" do
        expect {
          post symptoms_url, params: { symptom: invalid_attributes }
        }.to change(Symptom, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post symptoms_url, params: { symptom: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested symptom" do
        symptom = Symptom.create! valid_attributes
        patch symptom_url(symptom), params: { symptom: new_attributes }
        symptom.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the symptom" do
        symptom = Symptom.create! valid_attributes
        patch symptom_url(symptom), params: { symptom: new_attributes }
        symptom.reload
        expect(response).to redirect_to(symptom_url(symptom))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        symptom = Symptom.create! valid_attributes
        patch symptom_url(symptom), params: { symptom: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested symptom" do
      symptom = Symptom.create! valid_attributes
      expect {
        delete symptom_url(symptom)
      }.to change(Symptom, :count).by(-1)
    end

    it "redirects to the symptoms list" do
      symptom = Symptom.create! valid_attributes
      delete symptom_url(symptom)
      expect(response).to redirect_to(symptoms_url)
    end
  end
end
